version: '3'

services:

  # docker-compose run app bash
  # docker-compose run --service-ports app bash
  app:
    build: .
    image: cloudolife/col-hexo
    # image: cloudolife/col-hexo:node-15.9.0-alpine3.10-hexo-6.1.0
    ports:
      - "4000:4000"
    # restart: on-failure
    volumes:
      - ".:/app"