version: '3'

services:

  # docker-compose run app bash
  # docker-compose run --service-ports app bash
  app:
    build:
      context: .
    image: cloudolife/col-hexo
    ports:
      - "4000:4000"
    # restart: on-failure
    volumes:
      - .:/app